openapi: '3.0.2'
info:
  title: Checkout API
  description: API Spec for Checkout Store
  version: '1.0'
servers:
  - url: http://localhost:8080
paths:
  /checkout:
    post:
      description: Checkout Post
      summary: Checkout Post
      parameters:
        - in: header
          name: x-api-key
          schema:
            type: string
          required: true
      tags:
        - "Checkout API"
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                properties:
                  sku:
                    type: string
                  qty:
                    type: number
      responses:
        '200':
          description: Success checkout items
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    messsage: string
                    data: number